# This job is to test different maven profiles in sdk branch again Pull Request raised
# This workflow targets Java with Maven execution

name: Java SDK Test workflow for Maven on workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'The pull request number to build'
        required: true

jobs:
  comment-run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        java: [ '8', '11', '17' ]
        os: [ 'macos-latest', 'windows-latest', 'ubuntu-latest' ]
    name: JUnit Repo ${{ matrix.Java }} - ${{ matrix.os }} Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.inputs.pull_request_number }}/head
      - name: Fetch Commit SHA
        run: |
          git log -1 --format='%H'
          echo "commit_sha=$(git log -1 --format='%H')" >> $GITHUB_ENV
          echo "commit_sha=$(git log -1 --format='%H')" >> $env:GITHUB_ENV
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: status-check-in-progress
        env:
          job_name: JUnit Repo ${{ matrix.Java }} - ${{ matrix.os }} Sample
        with:
          github-token: ${{ github.token }}
          script: |
            const result = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: process.env.job_name,
              head_sha: process.env.commit_sha,
              status: 'in_progress'
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The status-check response : ${result.status} Response : ${JSON.stringify(result.response)}`)
            if (result.status !== 201) {
              console.log('Failed to create check run')
            }
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Change Directory to JUnit-4
        run: cd junit-4
      - name: Run mvn test
        run: |
          mvn compile
          mvn test
      - name: Run mvn profile sample
        run: |
          mvn compile
          mvn test -P sample
      - name: Run mvn profile local
        run: |
          mvn compile
          mvn test -P local
      - name: Change Directory to JUnit-5
        run: cd ../junit-5
      - name: Run mvn test
        run: |
          mvn compile
          mvn test
      - name: Run mvn profile single
        run: |
          mvn compile
          mvn test -P single
      - name: Run mvn profile local
        run: |
          mvn compile
          mvn test -P local
      - if: always()
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: status-check-completed
        env:
          conclusion: ${{ job.status }}
          job_name: TestNG Repo ${{ matrix.Java }} - ${{ matrix.os }} Sample
        with:
          github-token: ${{ github.token }}
          script: |
            const result = await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: process.env.job_name,
            head_sha: process.env.commit_sha,
            status: 'completed',
            conclusion: process.env.conclusion
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The status-check response : ${result.status} Response : ${JSON.stringify(result.response)}`)
            if (result.status !== 201) {
              console.log('Failed to create check run')
            }
